#!/usr/bin/env perl
use strict;
use warnings;

use FindBin;
use lib $FindBin::RealBin;

use DBI;
use DivDB;
use FileHandle;

my $file = shift @ARGV;

die "\nUsage:: $FindBin::Script all_star_times_file\n\n" unless defined $file;
die "\nUsage:: $FindBin::Script all_star_times_file\n\n" if @ARGV;

my $fh = new FileHandle($file) || die "\nFailed to open $file: $!\n\n";

my $dbh = &DivDB::getConnection;

$dbh->do("delete from all_star_times");
foreach (<$fh>)
{
  next unless /^(\d+)\s+([0-9:.]+)/;
  my $event = $1;
  my $time = $2;

  if($time=~/(\d+):(\S+)/)
  {
    $time = 60*$1 + $2;
  }

  $dbh->do("insert into all_star_times values ($event,$time)");
}
