insert into sdif_codes values (1, '1', 'USS');
insert into sdif_codes values (1, '2', 'Masters');
insert into sdif_codes values (1, '3', 'NCAA');
insert into sdif_codes values (1, '4', 'NCAA Div I');
insert into sdif_codes values (1, '5', 'NCAA Div II');
insert into sdif_codes values (1, '6', 'NCAA Div III');
insert into sdif_codes values (1, '7', 'YMCA');
insert into sdif_codes values (1, '8', 'FINA');
insert into sdif_codes values (1, '9', 'High School');
insert into sdif_codes values (2, 'AD', 'Adirondack');
insert into sdif_codes values (2, 'AK', 'Alaska');
insert into sdif_codes values (2, 'AM', 'Allegheny Mountain');
insert into sdif_codes values (2, 'AR', 'Arkansas');
insert into sdif_codes values (2, 'AZ', 'Arizona');
insert into sdif_codes values (2, 'BD', 'Border');
insert into sdif_codes values (2, 'CA', 'Southern California');
insert into sdif_codes values (2, 'CC', 'Central California');
insert into sdif_codes values (2, 'CO', 'Colorado');
insert into sdif_codes values (2, 'CT', 'Connecticut');
insert into sdif_codes values (2, 'FG', 'Florida Gold Coast');
insert into sdif_codes values (2, 'FL', 'Florida');
insert into sdif_codes values (2, 'GA', 'Georgia');
insert into sdif_codes values (2, 'GU', 'Gulf');
insert into sdif_codes values (2, 'HI', 'Hawaii');
insert into sdif_codes values (2, 'IA', 'Iowa');
insert into sdif_codes values (2, 'IE', 'Inland Empire');
insert into sdif_codes values (2, 'IL', 'Illinois');
insert into sdif_codes values (2, 'IN', 'Indiana');
insert into sdif_codes values (2, 'KY', 'Kentucky');
insert into sdif_codes values (2, 'LA', 'Louisiana');
insert into sdif_codes values (2, 'LE', 'Lake Erie');
insert into sdif_codes values (2, 'MA', 'Middle Atlantic');
insert into sdif_codes values (2, 'MD', 'Maryland');
insert into sdif_codes values (2, 'ME', 'Maine');
insert into sdif_codes values (2, 'MI', 'Michigan');
insert into sdif_codes values (2, 'MN', 'Minnesota');
insert into sdif_codes values (2, 'MR', 'Metropolitan');
insert into sdif_codes values (2, 'MS', 'Mississippi');
insert into sdif_codes values (2, 'MT', 'Montana');
insert into sdif_codes values (2, 'MV', 'Missouri Valley');
insert into sdif_codes values (2, 'MW', 'Midwestern');
insert into sdif_codes values (2, 'NC', 'North Carolina');
insert into sdif_codes values (2, 'ND', 'North Dakota');
insert into sdif_codes values (2, 'NE', 'New England');
insert into sdif_codes values (2, 'NI', 'Niagara');
insert into sdif_codes values (2, 'NJ', 'New Jersey');
insert into sdif_codes values (2, 'NM', 'New Mexico');
insert into sdif_codes values (2, 'NT', 'North Texas');
insert into sdif_codes values (2, 'OH', 'Ohio');
insert into sdif_codes values (2, 'OK', 'Oklahoma');
insert into sdif_codes values (2, 'OR', 'Oregon');
insert into sdif_codes values (2, 'OZ', 'Ozark');
insert into sdif_codes values (2, 'PC', 'Pacific');
insert into sdif_codes values (2, 'PN', 'Pacific Northwest');
insert into sdif_codes values (2, 'PV', 'Potomac Valley');
insert into sdif_codes values (2, 'SC', 'South Carolina');
insert into sdif_codes values (2, 'SD', 'South Dakota');
insert into sdif_codes values (2, 'SE', 'Southeastern');
insert into sdif_codes values (2, 'SI', 'San Diego Imperial');
insert into sdif_codes values (2, 'SN', 'Sierra Nevada');
insert into sdif_codes values (2, 'SR', 'Snake River');
insert into sdif_codes values (2, 'ST', 'South Texas');
insert into sdif_codes values (2, 'UT', 'Utah');
insert into sdif_codes values (2, 'VA', 'Virginia');
insert into sdif_codes values (2, 'WI', 'Wisconsin');
insert into sdif_codes values (2, 'WT', 'West Texas');
insert into sdif_codes values (2, 'WV', 'West Virginia');
insert into sdif_codes values (2, 'WY', 'Wyoming');
insert into sdif_codes values (3, '01', 'Meet Registrations');
insert into sdif_codes values (3, '02', 'Meet Results');
insert into sdif_codes values (3, '03', 'OVC');
insert into sdif_codes values (3, '04', 'National Age Group Record');
insert into sdif_codes values (3, '05', 'LSC Age Group Record');
insert into sdif_codes values (3, '06', 'LSC Motivational List');
insert into sdif_codes values (3, '07', 'National Records and Rankings');
insert into sdif_codes values (3, '08', 'Team Selection');
insert into sdif_codes values (3, '09', 'LSC Best Times');
insert into sdif_codes values (3, '10', 'USS Registration');
insert into sdif_codes values (3, '16', 'Top 16');
insert into sdif_codes values (3, '20', 'Vendor-defined code');
insert into sdif_codes values (4, 'AHO', 'Antilles Netherlands (Dutch West Indies)');
insert into sdif_codes values (4, 'ALB', 'Albania');
insert into sdif_codes values (4, 'ALG', 'Algeria');
insert into sdif_codes values (4, 'AND', 'Andorra');
insert into sdif_codes values (4, 'ANG', 'Angola');
insert into sdif_codes values (4, 'ANT', 'Antigua');
insert into sdif_codes values (4, 'ARG', 'Argentina');
insert into sdif_codes values (4, 'ARM', 'Armenia');
insert into sdif_codes values (4, 'ARU', 'Aruba');
insert into sdif_codes values (4, 'ASA', 'American Samoa');
insert into sdif_codes values (4, 'AUS', 'Australia');
insert into sdif_codes values (4, 'AUT', 'Austria');
insert into sdif_codes values (4, 'AZE', 'Azerbaijan');
insert into sdif_codes values (4, 'BAH', 'Bahamas');
insert into sdif_codes values (4, 'BAN', 'Bangladesh');
insert into sdif_codes values (4, 'BAR', 'Barbados');
insert into sdif_codes values (4, 'BEL', 'Belgium');
insert into sdif_codes values (4, 'BEN', 'Benin');
insert into sdif_codes values (4, 'BER', 'Bermuda');
insert into sdif_codes values (4, 'BHU', 'Bhutan');
insert into sdif_codes values (4, 'BIZ', 'Belize');
insert into sdif_codes values (4, 'BLS', 'Belarus');
insert into sdif_codes values (4, 'BOL', 'Bolivia');
insert into sdif_codes values (4, 'BOT', 'Botswana');
insert into sdif_codes values (4, 'BRA', 'Brazil');
insert into sdif_codes values (4, 'BRN', 'Bahrain');
insert into sdif_codes values (4, 'BRU', 'Brunei');
insert into sdif_codes values (4, 'BUL', 'Bulgaria');
insert into sdif_codes values (4, 'BUR', 'Burkina Faso');
insert into sdif_codes values (4, 'CAF', 'Central African Republic');
insert into sdif_codes values (4, 'CAN', 'Canada');
insert into sdif_codes values (4, 'CAY', 'Cayman Islands');
insert into sdif_codes values (4, 'CGO', 'People''s Rep. of Congo');
insert into sdif_codes values (4, 'CHA', 'Chad');
insert into sdif_codes values (4, 'CHI', 'Chile');
insert into sdif_codes values (4, 'CHN', 'People''s Rep. of China');
insert into sdif_codes values (4, 'CIV', 'Ivory Coast');
insert into sdif_codes values (4, 'CMR', 'Cameroon');
insert into sdif_codes values (4, 'COK', 'Cook Islands');
insert into sdif_codes values (4, 'COL', 'Columbia');
insert into sdif_codes values (4, 'CRC', 'Costa Rica');
insert into sdif_codes values (4, 'CRO', 'Croatia');
insert into sdif_codes values (4, 'CUB', 'Cuba');
insert into sdif_codes values (4, 'CYP', 'Cyprus');
insert into sdif_codes values (4, 'DEN', 'Denmark');
insert into sdif_codes values (4, 'DJI', 'Djibouti');
insert into sdif_codes values (4, 'DOM', 'Dominican Republic');
insert into sdif_codes values (4, 'ECU', 'Ecuador');
insert into sdif_codes values (4, 'EGY', 'Arab Republic of Egypt');
insert into sdif_codes values (4, 'ESA', 'El Salvador');
insert into sdif_codes values (4, 'ESP', 'Spain');
insert into sdif_codes values (4, 'EST', 'Estonia');
insert into sdif_codes values (4, 'ETH', 'Ethiopia');
insert into sdif_codes values (4, 'FIJ', 'Fiji');
insert into sdif_codes values (4, 'FIN', 'Finland');
insert into sdif_codes values (4, 'FRA', 'France');
insert into sdif_codes values (4, 'GAB', 'Gabon');
insert into sdif_codes values (4, 'GAM', 'Gambia');
insert into sdif_codes values (4, 'GBR', 'Great Britain');
insert into sdif_codes values (4, 'GEO', 'Georgia');
insert into sdif_codes values (4, 'GEQ', 'Equatorial Guinea');
insert into sdif_codes values (4, 'GER', 'Germany');
insert into sdif_codes values (4, 'GHA', 'Ghana');
insert into sdif_codes values (4, 'GRE', 'Greece');
insert into sdif_codes values (4, 'GRN', 'Grenada');
insert into sdif_codes values (4, 'GUA', 'Guatemala');
insert into sdif_codes values (4, 'GUI', 'Guinea');
insert into sdif_codes values (4, 'GUM', 'Guam');
insert into sdif_codes values (4, 'GUY', 'Guyana');
insert into sdif_codes values (4, 'HAI', 'Haiti');
insert into sdif_codes values (4, 'HKG', 'Hong Kong');
insert into sdif_codes values (4, 'HON', 'Honduras');
insert into sdif_codes values (4, 'HUN', 'Hungary');
insert into sdif_codes values (4, 'INA', 'Indonesia');
insert into sdif_codes values (4, 'IND', 'India');
insert into sdif_codes values (4, 'IRI', 'Islamic Rep. of Iran');
insert into sdif_codes values (4, 'IRL', 'Ireland');
insert into sdif_codes values (4, 'IRQ', 'Iraq');
insert into sdif_codes values (4, 'ISL', 'Iceland');
insert into sdif_codes values (4, 'ISR', 'Israel');
insert into sdif_codes values (4, 'ISV', 'Virgin Islands');
insert into sdif_codes values (4, 'ITA', 'Italy');
insert into sdif_codes values (4, 'IVB', 'British Virgin Islands');
insert into sdif_codes values (4, 'JAM', 'Jamaica');
insert into sdif_codes values (4, 'JOR', 'Jordan');
insert into sdif_codes values (4, 'JPN', 'Japan');
insert into sdif_codes values (4, 'KEN', 'Kenya');
insert into sdif_codes values (4, 'KGZ', 'Kyrghyzstan');
insert into sdif_codes values (4, 'KOR', 'Korea (South)');
insert into sdif_codes values (4, 'KSA', 'Saudi Arabia');
insert into sdif_codes values (4, 'KUW', 'Kuwait');
insert into sdif_codes values (4, 'KZK', 'Kazakhstan');
insert into sdif_codes values (4, 'LAO', 'Laos');
insert into sdif_codes values (4, 'LAT', 'Latvia');
insert into sdif_codes values (4, 'LBA', 'Libya');
insert into sdif_codes values (4, 'LBR', 'Liberia');
insert into sdif_codes values (4, 'LES', 'Lesotho');
insert into sdif_codes values (4, 'LIB', 'Lebanon');
insert into sdif_codes values (4, 'LIE', 'Liechtenstein');
insert into sdif_codes values (4, 'LIT', 'Lithuania');
insert into sdif_codes values (4, 'LUX', 'Luxembourg');
insert into sdif_codes values (4, 'MAD', 'Madagascar');
insert into sdif_codes values (4, 'MAR', 'Morocco');
insert into sdif_codes values (4, 'MAS', 'Malaysia');
insert into sdif_codes values (4, 'MAW', 'Malawi');
insert into sdif_codes values (4, 'MDV', 'Maldives');
insert into sdif_codes values (4, 'MEX', 'Mexico');
insert into sdif_codes values (4, 'MGL', 'Mongolia');
insert into sdif_codes values (4, 'MLD', 'Moldova');
insert into sdif_codes values (4, 'MLI', 'Mali');
insert into sdif_codes values (4, 'MLT', 'Malta');
insert into sdif_codes values (4, 'MON', 'Monaco');
insert into sdif_codes values (4, 'MOZ', 'Mozambique');
insert into sdif_codes values (4, 'MRI', 'Mauritius');
insert into sdif_codes values (4, 'MTN', 'Mauritania');
insert into sdif_codes values (4, 'MYA', 'Union of Myanmar');
insert into sdif_codes values (4, 'NAM', 'Namibia');
insert into sdif_codes values (4, 'NCA', 'Nicaragua');
insert into sdif_codes values (4, 'NED', 'The Netherlands');
insert into sdif_codes values (4, 'NEP', 'Nepal');
insert into sdif_codes values (4, 'NGR', 'Nigeria');
insert into sdif_codes values (4, 'NIG', 'Niger');
insert into sdif_codes values (4, 'NOR', 'Norway');
insert into sdif_codes values (4, 'NZL', 'New Zealand');
insert into sdif_codes values (4, 'OMA', 'Oman');
insert into sdif_codes values (4, 'PAK', 'Pakistan');
insert into sdif_codes values (4, 'PAN', 'Panama');
insert into sdif_codes values (4, 'PAR', 'Paraguay');
insert into sdif_codes values (4, 'PER', 'Peru');
insert into sdif_codes values (4, 'PHI', 'Philippines');
insert into sdif_codes values (4, 'PNG', 'Papau-New Guinea');
insert into sdif_codes values (4, 'POL', 'Poland');
insert into sdif_codes values (4, 'POR', 'Portugal');
insert into sdif_codes values (4, 'PRK', 'Democratic People''s Rep. of Korea');
insert into sdif_codes values (4, 'PUR', 'Puerto Rico');
insert into sdif_codes values (4, 'QAT', 'Qatar');
insert into sdif_codes values (4, 'ROM', 'Romania');
insert into sdif_codes values (4, 'RSA', 'South Africa');
insert into sdif_codes values (4, 'RUS', 'Russia');
insert into sdif_codes values (4, 'RWA', 'Rwanda');
insert into sdif_codes values (4, 'SAM', 'Western Samoa');
insert into sdif_codes values (4, 'SEN', 'Senegal');
insert into sdif_codes values (4, 'SEY', 'Seychelles');
insert into sdif_codes values (4, 'SIN', 'Singapore');
insert into sdif_codes values (4, 'SLE', 'Sierra Leone');
insert into sdif_codes values (4, 'SLO', 'Slovenia');
insert into sdif_codes values (4, 'SMR', 'San Marino');
insert into sdif_codes values (4, 'SOL', 'Solomon Islands');
insert into sdif_codes values (4, 'SOM', 'Somalia');
insert into sdif_codes values (4, 'SRI', 'Sri Lanka');
insert into sdif_codes values (4, 'SUD', 'Sudan');
insert into sdif_codes values (4, 'SUI', 'Switzerland');
insert into sdif_codes values (4, 'SUR', 'Surinam');
insert into sdif_codes values (4, 'SWE', 'Sweden');
insert into sdif_codes values (4, 'SWZ', 'Swaziland');
insert into sdif_codes values (4, 'SYR', 'Syria');
insert into sdif_codes values (4, 'TAN', 'Tanzania');
insert into sdif_codes values (4, 'TCH', 'Czechoslovakia');
insert into sdif_codes values (4, 'TGA', 'Tonga');
insert into sdif_codes values (4, 'THA', 'Thailand');
insert into sdif_codes values (4, 'TJK', 'Tadjikistan');
insert into sdif_codes values (4, 'TOG', 'Togo');
insert into sdif_codes values (4, 'TPE', 'Chinese Taipei');
insert into sdif_codes values (4, 'TRI', 'Trinidad & Tobago');
insert into sdif_codes values (4, 'TUN', 'Tunisia');
insert into sdif_codes values (4, 'TUR', 'Turkey');
insert into sdif_codes values (4, 'UAE', 'United Arab Emirates');
insert into sdif_codes values (4, 'UGA', 'Uganda');
insert into sdif_codes values (4, 'UKR', 'Ukraine');
insert into sdif_codes values (4, 'URU', 'Uruguay');
insert into sdif_codes values (4, 'USA', 'United States of America');
insert into sdif_codes values (4, 'VAN', 'Vanuatu');
insert into sdif_codes values (4, 'VEN', 'Venezuela');
insert into sdif_codes values (4, 'VIE', 'Vietnam');
insert into sdif_codes values (4, 'VIN', 'St. Vincent and the Grenadines');
insert into sdif_codes values (4, 'YEM', 'Yemen');
insert into sdif_codes values (4, 'YUG', 'Yugoslavia');
insert into sdif_codes values (4, 'ZAI', 'Zaire');
insert into sdif_codes values (4, 'ZAM', 'Zambia');
insert into sdif_codes values (4, 'ZIM', 'Zimbabwe');
insert into sdif_codes values (5, '0', 'Time Trials');
insert into sdif_codes values (5, '1', 'Invitational');
insert into sdif_codes values (5, '2', 'Regional');
insert into sdif_codes values (5, '3', 'LSC Championship');
insert into sdif_codes values (5, '4', 'Zone');
insert into sdif_codes values (5, '5', 'Zone Championship');
insert into sdif_codes values (5, '6', 'National Championship');
insert into sdif_codes values (5, '7', 'Juniors');
insert into sdif_codes values (5, '8', 'Seniors');
insert into sdif_codes values (5, '9', 'Dual');
insert into sdif_codes values (5, 'A', 'International');
insert into sdif_codes values (5, 'B', 'Open');
insert into sdif_codes values (5, 'C', 'League');
insert into sdif_codes values (7, '1', 'Region 1');
insert into sdif_codes values (7, '2', 'Region 2');
insert into sdif_codes values (7, '3', 'Region 3');
insert into sdif_codes values (7, '4', 'Region 4');
insert into sdif_codes values (7, '5', 'Region 5');
insert into sdif_codes values (7, '6', 'Region 6');
insert into sdif_codes values (7, '7', 'Region 7');
insert into sdif_codes values (7, '8', 'Region 8');
insert into sdif_codes values (7, '9', 'Region 9');
insert into sdif_codes values (7, 'A', 'Region 10');
insert into sdif_codes values (7, 'B', 'Region 11');
insert into sdif_codes values (7, 'C', 'Region 12');
insert into sdif_codes values (7, 'D', 'Region 13');
insert into sdif_codes values (7, 'E', 'Region 14');
insert into sdif_codes values (9, '2AL', 'Dual: USA and other country');
insert into sdif_codes values (9, 'FGN', 'Foreign');
insert into sdif_codes values (10, 'M', 'Male');
insert into sdif_codes values (10, 'F', 'Female');
insert into sdif_codes values (11, 'M', 'Male');
insert into sdif_codes values (11, 'F', 'Female');
insert into sdif_codes values (11, 'X', 'Mixed');
insert into sdif_codes values (12, '1', 'Freestyle');
insert into sdif_codes values (12, '2', 'Backstroke');
insert into sdif_codes values (12, '3', 'Breaststroke');
insert into sdif_codes values (12, '4', 'Butterfly');
insert into sdif_codes values (12, '5', 'Individual Medley');
insert into sdif_codes values (12, '6', 'Freestyle Relay');
insert into sdif_codes values (12, '7', 'Medley Relay');
insert into sdif_codes values (13, '1', 'Short Course Meters');
insert into sdif_codes values (13, '2', 'Short Course Yards');
insert into sdif_codes values (13, '3', 'Long Course Meters');
insert into sdif_codes values (13, 'S', 'Short Course Meters');
insert into sdif_codes values (13, 'Y', 'Short Course Yards');
insert into sdif_codes values (13, 'L', 'Long Course Meters');
insert into sdif_codes values (13, 'X', 'Disqualified');
insert into sdif_codes values (14, 'U', 'no lower limit (left character only)');
insert into sdif_codes values (14, 'O', 'no upper limit (right character only)');
insert into sdif_codes values (14, '1', 'Novice times');
insert into sdif_codes values (14, '2', 'B standard times');
insert into sdif_codes values (14, 'P', 'BB standard times');
insert into sdif_codes values (14, '3', 'A standard times');
insert into sdif_codes values (14, '4', 'AA standard times');
insert into sdif_codes values (14, '5', 'AAA standard times');
insert into sdif_codes values (14, '6', 'AAAA standard times');
insert into sdif_codes values (14, 'J', 'Junior standard times');
insert into sdif_codes values (14, 'S', 'Senior standard times');
insert into sdif_codes values (15, 'C', 'Cumulative splits supplied');
insert into sdif_codes values (15, 'I', 'Interval splits supplied');
insert into sdif_codes values (16, 'A', 'Swimmer is attached to team');
insert into sdif_codes values (16, 'U', 'Swimmer is swimming unattached');
insert into sdif_codes values (17, 'E', 'Eastern Zone');
insert into sdif_codes values (17, 'S', 'Southern Zone');
insert into sdif_codes values (17, 'C', 'Central Zone');
insert into sdif_codes values (17, 'W', 'Western Zone');
insert into sdif_codes values (18, 'GOLD', 'Gold');
insert into sdif_codes values (18, 'SILV', 'Silver');
insert into sdif_codes values (18, 'BRNZ', 'Bronze');
insert into sdif_codes values (18, 'BLUE', 'Blue');
insert into sdif_codes values (18, 'RED', 'Red (note that fourth character is a space)');
insert into sdif_codes values (18, 'WHIT', 'White');
insert into sdif_codes values (19, 'P', 'Prelims');
insert into sdif_codes values (19, 'F', 'Finals');
insert into sdif_codes values (19, 'S', 'Swim-offs');
insert into sdif_codes values (20, 'NT', 'No Time');
insert into sdif_codes values (20, 'NS', 'No Swim (or No Show)');
insert into sdif_codes values (20, 'DNF', 'Did Not Finish');
insert into sdif_codes values (20, 'DQ', 'Disqualified');
insert into sdif_codes values (20, 'SCR', 'Scratch');
insert into sdif_codes values (21, 'R', 'Renew');
insert into sdif_codes values (21, 'N', 'New');
insert into sdif_codes values (21, 'C', 'Change');
insert into sdif_codes values (21, 'D', 'Delete');
insert into sdif_codes values (22, '1', 'Season 1');
insert into sdif_codes values (22, '2', 'Season 2');
insert into sdif_codes values (22, 'N', 'Year-round');
insert into sdif_codes values (24, '0', 'Not on team for this swim');
insert into sdif_codes values (24, '1', 'First leg');
insert into sdif_codes values (24, '2', 'Second leg');
insert into sdif_codes values (24, '3', 'Third leg');
insert into sdif_codes values (24, '4', 'Fourth leg');
insert into sdif_codes values (24, 'A', 'Alternate');
insert into sdif_codes values (26, 'Q', 'African American');
insert into sdif_codes values (26, 'R', 'Asian or Pacific Islander');
insert into sdif_codes values (26, 'S', 'Caucasian');
insert into sdif_codes values (26, 'T', 'Hispanic');
insert into sdif_codes values (26, 'U', 'Native American');
insert into sdif_codes values (26, 'V', 'Other');
insert into sdif_codes values (26, 'W', 'Decline');
